

service: serverless-step-function-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

plugins:
  - serverless-step-functions

functions:
  checkWallet:
    handler: handler.checkWallet
  getNormalTransactions:
    handler: handler.getNormalTransactions

stepFunctions:
  stateMachines:
    processWalletFlow:
      name: processWalletFlow
      definition:
        StartAt: checkWallet
        States:
          checkWallet:
            Type: Task
            Resource:
              Fn::GetAtt: [checkWallet, Arn]
            Next: getNormalTransactions
          getNormalTransactions:
            Type: Task
            Resource:
              Fn::GetAtt: [getNormalTransactions, Arn]
            End: true

